name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout master
      uses: actions/checkout@v1
      with:
        submodules: true

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.73.0'
        extended: true

    - name: Build
      run: hugo --minify


    - name: Setup go
      uses: actions/setup-go@v3
      with:
        go-version: '^1.19'
    
    - name: Hugo deploy github pages
      uses: benmatselby/hugo-deploy-gh-pages@master
      env:
        HUGO_VERSION: 0.101.0
        HUGO_EXTENDED: true
        TARGET_REPO: eguidotti/website
        TOKEN: ${{ secrets.TOKEN }}
        CNAME: guidotti.dev