name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout master
      uses: actions/checkout@v1
      with:
        submodules: true

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: '^1.19'

    - name: Hugo Deploy GitHub Pages
      uses: benmatselby/hugo-deploy-gh-pages@master
      env:
        HUGO_VERSION: 0.101.0
        TARGET_REPO: eguidotti/website
        TOKEN: ${{ secrets.TOKEN }}
        CNAME: guidotti.dev